### ISSUE TITLE
求问如何同时预览一个预制体中的多个粒子系统

### ISSUE THREAD

**Issue by guan-dl** [akof1314/UnityParticleSystemPreview#10]
我这里有不少粒子系统放在了一个prefab里面，通过您的插件确实可以预览，但是这个插件只会播放第一个粒子系统，其他同级的粒子并不能播放，求助如何解决

**Comment by guan-dl** [comment]
就是说这个锁定粒子能否锁定多个粒子系统？

**Comment by guan-dl** [comment]
ParticleSystemPreview.cs我在这个文件中的CreatePreviewInstances函数增加了判断，直接给根节点加粒子系统组件（不会影响资源）解决了这个问题~
private void CreatePreviewInstances()
{
	//前面的代码
//直接给根节点加一个粒子系统节点保证锁定粒子
            if(m_PreviewInstance.GetComponent<ParticleSystem>() == null)
            {
                m_PreviewInstance.AddComponent<ParticleSystem>().enableEmission = false;
            }

}
      
另外，使用过程中发现，多选普通模型的prefab的时候，不能正确预览出各个模型的样子（比如多选选中了三个不同的模型，预览界面只能绘制出3个一样的模型），解决方法如下
ParticleSystemGameObjectEditor.cs文件 修改了OnpreviewGUI方法
static PropertyInfo m_TargetIndexInfo;
        PropertyInfo TargetIndexInfo
        {
            get
            {
                if (m_TargetIndexInfo == null)
                {
                    var assembly = Assembly.GetAssembly(typeof(Editor));
                    Type realTypeEditor = assembly.GetType("UnityEditor.Editor");
                    m_TargetIndexInfo = realTypeEditor.GetProperty("referenceTargetIndex", BindingFlags.NonPublic | BindingFlags.Instance);
                }
                return m_TargetIndexInfo;
            }
        }
public override void OnPreviewGUI(Rect r, GUIStyle background)
        {
            if (IsShowParticleSystemPreview())
            {
                ParticlePreview.OnPreviewGUI(r, background);
            }
            else
            {
                //在资源窗口（Project窗口中）点击的时候，会通过AssetImporterEditor这个类去驱动预览界面的绘制，
                //由于无法重写Editor类中的referenceTargetIndex属性，没有办法把这个属性指向创建出来的GameObjectInspector的referenceTargetIndex，
                //在多选预览的时候GameObjectInspector的referenceTargetIndex就没有办法被正常驱动增长，所以多选预览画出来的都是一个模型，很垃圾，
                //这里通过反射拿到当前这个类的referenceTargetIndex（这个是正常增长的），把这个赋值给GameObjectInspector，让他正常绘制出来~
                TargetIndexInfo.SetValue(baseEditor, TargetIndexInfo.GetValue(this));
                baseEditor.OnPreviewGUI(r, background);
            }
        }

**Comment by akof1314** [comment]
很棒，可以提交合并
