### ISSUE TITLE
不可以直接拖动物体到场景

### ISSUE THREAD

**Issue by cn00** [akof1314/UnityParticleSystemPreview#3]
使用此插件后, 不可以直接拖动物体到场景, 请问这个特性是如何实现点, 谢谢

**Comment by akof1314** [comment]
我这边是可以拖动到场景上的，你那边是使用什么版本呢

**Comment by cn00** [comment]
插件是 master 分支版本, unity 是 5.6.3f1, 
做编辑器需要关闭默认拖入放置物体, 自己接管拖入场景窗口的控制, 
就想知道这是怎么关闭的

**Comment by akof1314** [comment]
这个插件并没有实现这个效果。 如果你想实现，可以监听对象树变化事件，当添加的时候，将它移除掉。

**Comment by nxlwnm** [comment]
5.6.5f1有同样的问题，请问是哪个地方导致的

**Comment by akof1314** [comment]
@nxlwnm 刚修改，试试看
