### ISSUE TITLE
Not Compatible with Unity v2018.2+

### ISSUE THREAD

**Issue by VikingAntics** [akof1314/UnityParticleSystemPreview#4]
Hi,
I know this hasn't been updated in quite some time, but if possible, can you please make this compatible with Unity 2018.2+?  It is a great asset and we greatly appreciate your generosity in sharing it with the Unity community.  

Thank you for your help.

**Comment by GuardHei** [comment]
Met the same problem but I think that it is easy to fix.

Just use reflection to check all the properties class `UnityEditor.ParticleSystemEditorUtils` has. You'll find out only the names changed, so errors occur when tried to access these properties via reflection. Basically, all you need is go to script `ParticleSystemEditorUtilsReflect.cs` and change the names of the properties in the public static method `InitType()`

**Comment by akof1314** [comment]
@VikingAntics Fix

**Comment by VikingAntics** [comment]
Thank you very much!  You made my day! 👍
