### ISSUE TITLE
插件容易导致Unity2018宕机

### ISSUE THREAD

**Issue by nxlwnm** [akof1314/UnityParticleSystemPreview#5]
![image](https://user-images.githubusercontent.com/7479188/51163888-30a99980-18d6-11e9-801b-a4c206463655.png)
部分堆栈如图
大概是美术在拼场景时经常undo redo带特效的预制时容易宕机
ParticleSystemGameObjectEditor.OnDisable
DestroyImmediate(baseEditor);
猜测是 如果baseEditor已经为空会创建一个新的Editor，但是此时targets已销毁，unity内部未作检查导致宕机

**Comment by akof1314** [comment]
收到

**Comment by akof1314** [comment]
不再手动清baseEditor
