### ISSUE TITLE
插件生命周期的一些问题

### ISSUE THREAD

**Issue by nxlwnm** [akof1314/UnityParticleSystemPreview#6]
堆栈如图：
![image](https://user-images.githubusercontent.com/7479188/52565065-b884b400-2e40-11e9-9332-28be1031037e.png)

问题出在
![image](https://user-images.githubusercontent.com/7479188/52565087-ccc8b100-2e40-11e9-9af4-d26dc9f3f889.png)
m_PreviewCache在OnEnable时初始化，看堆栈是m_BaseEditor被实例化后立马被销毁，导致m_PreviewCache为空

翻了一下类似的重载editor的插件，都没有在OnDisable时手动清baseEditor，实际上也应该不会导致内存问题
![image](https://user-images.githubusercontent.com/7479188/52565242-3e086400-2e41-11e9-9bc8-3cdacc6195b8.png)
编辑器在缓存Inspector时会自动判断并销毁多余的inspector

**Comment by akof1314** [comment]
@nxlwnm 好的，我再加个判断
